services:
  backend:
    build:
      context: ./backend  
    ports:
      - "5000:5000"  
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map port 3000 on the host to port 80 in the container (Nginx serves on port 80)
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
